In [2]:
import pandas as pd
import numpy as np

In [3]:
from google.colab import files
uploaded = files.upload()

Saving train_u6lujuX_CVtuZ9i (1).csv to train_u6lujuX_CVtuZ9i (1).csv

In [4]:
df = pd.read_csv("train_u6lujuX_CVtuZ9i (1).csv")

In [5]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [6]:
df.tail()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [7]:
df.shape

(614, 13)

In [8]:
df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [9]:
df.isnull().sum().sort_values(ascending=False)

Credit_History       50
Self_Employed        32
LoanAmount           22
Dependents           15
Loan_Amount_Term     14
Gender               13
Married               3
Education             0
Loan_ID               0
CoapplicantIncome     0
ApplicantIncome       0
Property_Area         0
Loan_Status           0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df["Loan_Status"].value_counts()

Loan_Status
Y    422
N    192
Name: count, dtype: int64

In [12]:
df["Credit_History"] = df["Credit_History"].fillna(df["Credit_History"].mean())

In [13]:
df["Credit_History"].isnull().sum()

np.int64(0)

In [14]:
df["Self_Employed"].value_counts()

Self_Employed
No     500
Yes     82
Name: count, dtype: int64

In [15]:
df["Self_Employed"] = df["Self_Employed"].fillna(df["Self_Employed"].mode()[0])

In [16]:
df["Self_Employed"].isnull().sum()

np.int64(0)

In [17]:
Q1 = df["LoanAmount"].quantile(0.25)
Q2 = df["LoanAmount"].quantile(0.75)

In [18]:
iqr = Q2 - Q1

In [19]:
lower_limit = Q1 - 1.5 * iqr
upper_limit = Q2 + 1.5 * iqr

In [20]:
outlier = df["LoanAmount"][(df["LoanAmount"]<lower_limit) | (df["LoanAmount"]>upper_limit)]

In [21]:
outlier

9      349.0
21     315.0
34     320.0
54     286.0
67     312.0
126    370.0
130    650.0
135    290.0
155    600.0
161    275.0
171    700.0
177    495.0
233    280.0
253    279.0
258    304.0
260    330.0
278    436.0
308    480.0
324    300.0
325    376.0
333    490.0
351    308.0
369    570.0
372    380.0
381    296.0
391    275.0
409    360.0
432    405.0
487    500.0
506    480.0
514    311.0
523    480.0
525    400.0
536    324.0
561    600.0
572    275.0
592    292.0
600    350.0
604    496.0
Name: LoanAmount, dtype: float64

In [22]:
df["LoanAmount"] = df["LoanAmount"].fillna(df["LoanAmount"].median())

In [23]:
df["LoanAmount"].isnull().sum()

np.int64(0)

In [24]:
df["Dependents"] = df["Dependents"].fillna(df["Dependents"].mode()[0])

In [25]:
df["Loan_Amount_Term"] = df["Loan_Amount_Term"].fillna(df["Loan_Amount_Term"].mean())

In [26]:
df["Gender"] = df["Gender"].fillna(df["Gender"].mode()[0])

In [27]:
df["Married"] = df["Married"].fillna(df["Married"].mode()[0])

In [63]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [29]:
df["Loan_Status"] = df["Loan_Status"].map({
    "Y":1,"N":0
    })

In [30]:
df["Gender"] = df["Gender"].map({
    "Male":1,"Female":0
    })

In [31]:
df["Married"] = df["Married"].map({
    "Yes":1,"No":0
    })

In [32]:
df["Education"] = df["Education"].map({
    "Graduate":1,"Not Graduate":0
    })

In [33]:
df["Self_Employed"] = df["Self_Employed"].map({
    "Yes":1,"No":0
    })

In [34]:
df["Property_Area"] = df["Property_Area"].map({
    "Urban":1,"Semiurban":2,"Rural":3
    })

In [35]:
df["Dependents"] = df["Dependents"].replace("3+", "3")

In [36]:
df["Dependents"] = pd.to_numeric(df["Dependents"], errors="coerce")

In [37]:
x = df.drop("Loan_Status", axis=1)
y = df["Loan_Status"]

In [81]:
from sklearn.model_selection import train_test_split

In [82]:
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

In [83]:
x_test.shape

(123, 12)

In [84]:
x_train.shape

(491, 12)

In [85]:
from imblearn.over_sampling import SMOTE

In [86]:
smote = SMOTE(random_state=42)

In [89]:
x_train_smote, y_train_smote = smote.fit_resample(x_train, y_train)

In [88]:
x_train = x_train.drop("Loan_ID", axis=1)
x_test = x_test.drop("Loan_ID", axis=1)

In [72]:
x = df.drop("Loan_Status", axis=1)
y = df["Loan_Status"]

In [55]:
df["Dependents"] = pd.to_numeric(df["Dependents"], errors="coerce")

In [90]:
from sklearn.linear_model import LogisticRegression

In [91]:
model = LogisticRegression(random_state=42)

In [93]:
model.fit(x_train_smote, y_train_smote)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(random_state=42)

In [95]:
y_pred = model.predict(x_test)

In [96]:
from sklearn.metrics import confusion_matrix

In [97]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[23 20]
 [ 9 71]]

In [98]:
from sklearn.metrics import accuracy_score

In [99]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.7642276422764228

In [100]:
from sklearn.metrics import classification_report

In [101]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.72      0.53      0.61        43
           1       0.78      0.89      0.83        80

    accuracy                           0.76       123
   macro avg       0.75      0.71      0.72       123
weighted avg       0.76      0.76      0.75       123

In [102]:
from sklearn.ensemble import RandomForestClassifier

In [103]:
rf = RandomForestClassifier(
    random_state=42
)

In [104]:
model = LogisticRegression()

In [105]:
rf = RandomForestClassifier()

In [107]:
rf.fit(x_train_smote, y_train_smote)

RandomForestClassifier()

In [109]:
rf_pred = rf.predict(x_test)

In [110]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, rf_pred)

0.7560975609756098

In [111]:
from sklearn.metrics import classification_report

print(classification_report(y_test, rf_pred))

              precision    recall  f1-score   support

           0       0.78      0.42      0.55        43
           1       0.75      0.94      0.83        80

    accuracy                           0.76       123
   macro avg       0.77      0.68      0.69       123
weighted avg       0.76      0.76      0.73       123

In [112]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, rf_pred)

array([[18, 25],
       [ 5, 75]])